using System;
namespace SuperMarketApi.Models.Enum
{
    public enum TransTypeEnum
    {
        Salary = 1,
        Salary_Advance = 2,
        Purchase = 3,
        Maintenance = 4,
        Credit = 5,
        Credit_Repay = 6,
        Debt = 7,
        Debt_Repay = 8,
        Sales = 9,
        Send_to_Store = 10,
        Receive_from_Store = 11,
        Swiping = 12,
        Swiping_Settle = 13,
        Affiliate = 14,
        Affiliate_Settle = 15,
        Opening_Balance = 16,
        Coupon_Sales = 17,
        Coupon_Redeem = 18,
        Bank_Deposit = 19,
        Bank_Withdraw = 20,
        Bank_Misc_In = 21,
        Bank_Misc_Out = 22,
        Cheque_In_Encash = 23,
        Cheque_Out_Encash = 24,
        Cheque_In_Returned = 25,
        Cheque_Out_Returned = 26,
        Cheque_In_Return = 27,
        Cheque_Out_Return = 28,
        Cheque_In_Bounce = 29,
        Cheque_Out_Bounce = 30,
        Misc_In = 31,
        Misc_Out = 32,
        Store_Closing = 33,
        Bank_Closing = 34,
        SalesOrder = 35,
        Purchase_Refund = 36,
        Maintenance_Refund = 37,
        Sales_Refund = 38,
        Bank_To_Bank = 39,
        Cake_Sales = 40,
        Cake_Refund = 41,
        Internal = 42,
        Internal_Refund = 43,
        SalaryHold_Pay = 44,
        Emp_Refund = 45,
    }
}